### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by winezer0** [R4gd0ll/I-Wanna-Get-All#12]
![image](https://github.com/R4gd0ll/I-Wanna-Get-All/assets/46115146/e89c0d62-5732-4fa1-9e03-648ec514e21c)

**Comment by R4gd0ll** [comment]
试试这个https://github.com/R4gd0ll/I-Wanna-Get-All/releases/tag/I-Wanna-Get-All-v1.2

**Comment by winezer0** [comment]
OK 感谢 已解决
